In [1]:
import numpy as np

original_list = [12.23, 13.32, 100, 36.32]

numpy_array = np.array(original_list)
print(numpy_array)

[ 12.23  13.32 100.    36.32]


In [6]:
import numpy as np

array = np.arange(2, 11)
print(array)

matrix = array.reshape(3, 3)
print(matrix)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [11]:
import numpy as np

array = np.zeros(10)
print(array)

new_array = array.copy()
new_array[6] = 11
print(new_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [ ]:
import numpy as np

original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
print(original_array)

reversed_array = original_array.copy()
print(reversed_array[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [17]:
import numpy as np

array = np.ones((5,5))
print(array)

array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
import numpy as np

array = np.ones((5, 5))
print(array)

array[[0,4],[0,4]] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0.]]


In [24]:
import numpy as np

array = np.ones((3, 3))
print(array)

border_array = np.zeros((5, 5))
border_array[1:-1, 1:-1] = array
print(border_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
import numpy as np

checkboard_array = np.ones((8, 8))
print(checkboard_array)

checkboard_array[::2, ::2] = 0
checkboard_array[1::2, 1::2] = 0
print()
print(checkboard_array)


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [31]:
import numpy as np

list = [1, 2, 3, 4, 5, 7, 8]
list_array = np.array(list)
print(list_array)

tuple = ((8, 4, 6),
         (1, 2, 3))
tuple_array = np.array(tuple)
print(tuple_array)


[1 2 3 4 5 7 8]
[[8 4 6]
 [1 2 3]]


In [35]:
import numpy as np

array = np.array([10, 20, 30])
print(array)
new_array = np.append(array , [60, 70, 80, 90])
print(new_array)

[10 20 30]
[10 20 30 60 70 80 90]


In [36]:
import numpy as np

complex_array = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print(complex_array.real)
print(complex_array.imag)

[1.         0.70710678]
[0.         0.70710678]


In [37]:
import numpy as np

array = np.array([5, 10, 15])

print("size of the array: ", array.size)
print("Length of one array element in bytes: ", array.itemsize)
print("Total bytes consumed by the elements of the array: ",array.nbytes)

size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [ ]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])

common_values = []
for value in arr1:
    if value in arr2:
        common_values.append(value)
common_values = np.array(common_values)

print("common values: ",common_values )

common values:  [10 40]


In [44]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])

diff_array = []
for value in arr1:
    if value not in arr2:
        diff_array.append(value)

diff_array = np.array(diff_array)
print(diff_array)

[ 0 20 60 80]


In [45]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])

res_array = []
for value in arr1:
    if value not in arr2:
        res_array.append(value)

for value in arr2:
    if value not in arr1:
        res_array.append(value)

res_array = np.array(sorted(res_array))
print(res_array)


[ 0 20 30 50 60 70 80]
