1.convert list to 1d array

In [1]:
import numpy as np

original_list = [12.23, 13.32, 100, 36.32]

numpy_array = np.array(original_list)
print(numpy_array)

[ 12.23  13.32 100.    36.32]


2.created 3x3 matrix with range of 2 t0 10

In [6]:
import numpy as np

array = np.arange(2, 11)
print(array)

matrix = array.reshape(3, 3)
print(matrix)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.create a null vector of size 10 and updated 6th value to 11

In [11]:
import numpy as np

array = np.zeros(10)
print(array)

new_array = array.copy()
new_array[6] = 11
print(new_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4.program to reverse array

In [ ]:
import numpy as np

original_array = np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])
print(original_array)

reversed_array = original_array.copy()
print(reversed_array[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5.created 2d array with 1 border and 0 inside

In [17]:
import numpy as np

array = np.ones((5,5))
print(array)

array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6.program to add border (with filled zeros) around existing array

In [24]:
import numpy as np

array = np.ones((3, 3))
print(array)

border_array = np.zeros((5, 5))
border_array[1:-1, 1:-1] = array
print(border_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7.created 8x8 matrix and fill it with checkerboard pattern

In [29]:
import numpy as np

checkboard_array = np.ones((8, 8))
print(checkboard_array)

checkboard_array[::2, ::2] = 0
checkboard_array[1::2, 1::2] = 0
print()
print(checkboard_array)


[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8.convert list and tuple to array

In [31]:
import numpy as np

list = [1, 2, 3, 4, 5, 7, 8]
list_array = np.array(list)
print(list_array)

tuple = ((8, 4, 6),
         (1, 2, 3))
tuple_array = np.array(tuple)
print(tuple_array)


[1 2 3 4 5 7 8]
[[8 4 6]
 [1 2 3]]


9.append value to the end of an array

In [35]:
import numpy as np

array = np.array([10, 20, 30])
print(array)
new_array = np.append(array , [60, 70, 80, 90])
print(new_array)

[10 20 30]
[10 20 30 60 70 80 90]


10.find real and imaginary parts

In [36]:
import numpy as np

complex_array = np.array([1.00000000+0.j, 0.70710678+0.70710678j])
print(complex_array.real)
print(complex_array.imag)

[1.         0.70710678]
[0.         0.70710678]


11.find number of elements of an array, length of each element and total bytes consumed by the elements

In [37]:
import numpy as np

array = np.array([5, 10, 15])

print("size of the array: ", array.size)
print("Length of one array element in bytes: ", array.itemsize)
print("Total bytes consumed by the elements of the array: ",array.nbytes)

size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


12.find common values between two arrays

In [ ]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])

common_values = []
for value in arr1:
    if value in arr2:
        common_values.append(value)
common_values = np.array(common_values)

print("common values: ",common_values )

common values:  [10 40]


13.values in array1 that are not in array2...return it sorted

In [47]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])

diff_array = []
for value in arr1:
    if value not in arr2:
        diff_array.append(value)

diff_array = np.array(sorted(diff_array))
print(diff_array)

[ 0 20 60 80]


14.unique values that are only in one array(not both)..return it in sorted

In [45]:
import numpy as np

arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])

res_array = []
for value in arr1:
    if value not in arr2:
        res_array.append(value)

for value in arr2:
    if value not in arr1:
        res_array.append(value)

res_array = np.array(sorted(res_array))
print(res_array)


[ 0 20 30 50 60 70 80]


15.compare two arrays

In [51]:
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([4, 5])

print("if a>b: ", arr1 > arr2)
print("if a>=b: ", arr1 >= arr2)
print("if a<b: ", arr1 < arr2)
print("if a<=b: ", arr1 <= arr2)

if a>b:  [False False]
if a>=b:  [False False]
if a<b:  [ True  True]
if a<=b:  [ True  True]


16.create a contigious flattend array

In [63]:
import numpy as np

array = np.array([[10, 20, 30],[20, 40, 50]])
new_array = array.reshape(-1)

print(new_array)

[10 20 30 20 40 50]


17.change dat type of an array

In [68]:
import numpy as np

array = np.array([[2, 4, 6], [6, 8, 10]], dtype = 'int32')
print(array)
print(array.dtype)

new_array = array.astype('float64')
print(new_array)
print(new_array.dtype)

[[ 2  4  6]
 [ 6  8 10]]
int32
[[ 2.  4.  6.]
 [ 6.  8. 10.]]
float64


18.crete 2d array with ones on a diagonal and zeros

In [7]:
import numpy as np

array =np.zeros((3,3))
print(array)

for i in range(3):
    array[i][i] = 1
print("added 1 to diagonal: ")
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
added 1 to diagonal: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19.create array which looks like given array

In [37]:
import numpy as np

array = np.zeros((4, 3))

for i in range(4):
    for j in range(i):
         array[i][j] = 1

print(array)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20.concatenate 2 dimesional array

In [26]:
import numpy as np

array1 = np.array([[0, 1, 3],[5, 7, 9]])
array2 = np.array([[0, 2, 4],[6, 8, 10]])


new_array = np.concatenate((array1, array2), axis =1)
print(new_array)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22.create array and multiple each element with 3

In [29]:
import numpy as np

array =np.arange(0, 12)
array = array.reshape(3, 4)
print(array)

array = array * 3
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


27.remove specific elements

In [31]:
import numpy as np

original_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(original_array)

new_array = np.delete(original_array,[1, 4, 5])
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  30  40  70  80  90 100]
